// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"context"
	"io"
	"net/http/httptest"
	"os"
	"testing"
	"time"

	"github.com/riverqueue/river"
	"github.com/riverqueue/river/riverdriver/riverpgxv5"
	"github.com/stretchr/testify/require"

	"github.com/jarida-io/climateshield/internal/briefing"
	"github.com/jarida-io/climateshield/internal/briefing/facts"
	"github.com/jarida-io/climateshield/internal/briefing/facts/factstest"
	"github.com/jarida-io/climateshield/internal/briefing/mock"
	"github.com/jarida-io/climateshield/internal/platform/logging"
	"github.com/jarida-io/climateshield/internal/publicapi"
	"github.com/jarida-io/climateshield/internal/store/db"
	"github.com/jarida-io/climateshield/internal/store/testdb"
)

// The demo's briefing step is the most quotable output this pillar has: it is
// what a reviewer sees on a live call. This test asserts the words, because
// "prints something plausible" is exactly the failure mode the whole project
// exists to avoid.

func captureStdout(t *testing.T, fn func()) string {
	t.Helper()
	r, w, err := os.Pipe()
	require.NoError(t, err)
	saved := os.Stdout
	os.Stdout = w
	defer func() { os.Stdout = saved }()

	done := make(chan string, 1)
	go func() {
		var buf bytes.Buffer
		_, _ = io.Copy(&buf, r)
		done <- buf.String()
	}()

	fn()
	require.NoError(t, w.Close())
	return <-done
}

func TestReportBriefingPrintsProvenanceWithTheText(t *testing.T) {
	pool := testdb.Pool(t)
	ctx := context.Background()
	q := db.New(pool)

	body, err := mock.Template(factstest.Sample(), facts.LangEN, mock.Notice{Kind: mock.NoticeNoModel})
	require.NoError(t, err)
	canon, hash, err := facts.Canonical(factstest.Sample())
	require.NoError(t, err)
	_, err = q.UpsertBriefing(ctx, db.UpsertBriefingParams{
		AreaID: "kisumu", Lang: "en", FactsHash: hash[:], FactsJson: canon,
		Generator: "mock", Model: "none", PromptVersion: "template-v1",
		Body: body, Grounded: true, GroundingNotes: []byte("null"),
		Status: briefing.StatusServed,
	})
	require.NoError(t, err)

	api := httptest.NewServer(
		publicapi.NewServer(pool, logging.New(io.Discard, "error")).Router(nil, nil))
	t.Cleanup(api.Close)

	riverClient, err := river.NewClient(riverpgxv5.New(pool), &river.Config{})
	require.NoError(t, err)

	runCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	out := captureStdout(t, func() {
		require.NoError(t, reportBriefing(runCtx, riverClient, api.URL, "Kisumu"))
	})

	// A reading aid: `go test ./cmd/demo -run TestReportBriefing -v` shows the
	// exact block a reviewer sees during `make demo`.
	t.Logf("\n%s", out)

	require.Contains(t, out, "--- County briefing ---")
	require.Contains(t, out, "Generated by a deterministic template — no language model ran")
	require.Contains(t, out, "[mock] no language model ran")
	require.Contains(t, out, "Cholera: HIGH")
	require.Contains(t, out, "facts behind it: 4 scored diseases, window 2026-09-10 to 2026-09-23")
	require.Contains(t, out, "/v1/briefings?area=Kisumu&lang=sw")
	require.NotContains(t, out, "+2547")
}

func TestShortHash(t *testing.T) {
	require.Equal(t, "0123456789ab…", short("0123456789abcdef"))
	require.Equal(t, "abc", short("abc"))
}
