// SPDX-License-Identifier: Apache-2.0

// Package store owns database access: connection pooling, embedded
// migrations, and the guarded erasure path. Query code is generated by sqlc
// into internal/store/db.
package store

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/jarida-io/climateshield/internal/store/db"
)

// Connect opens a pgx pool and verifies connectivity.
func Connect(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("store: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: %w", err)
	}
	return pool, nil
}

// WithErasure runs fn inside a transaction that is allowed to delete
// immunization events. This is the ONLY sanctioned way past the append-only
// trigger, and it exists solely for ForgetChild (right-to-erasure). The flag
// is SET LOCAL, so it dies with the transaction.
func WithErasure(ctx context.Context, pool *pgxpool.Pool, fn func(q *db.Queries) error) error {
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("store: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, "SET LOCAL climateshield.allow_erasure = 'on'"); err != nil {
		return fmt.Errorf("store: %w", err)
	}
	if err := fn(db.New(tx)); err != nil {
		return err
	}
	return tx.Commit(ctx)
}
