// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAlertsByStatus = `-- name: CountAlertsByStatus :many
SELECT status, count(*) AS n FROM alerts GROUP BY status ORDER BY status
`

type CountAlertsByStatusRow struct {
	Status string
	N      int64
}

func (q *Queries) CountAlertsByStatus(ctx context.Context) ([]CountAlertsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countAlertsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAlertsByStatusRow
	for rows.Next() {
		var i CountAlertsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const existsAlertForChildRisk = `-- name: ExistsAlertForChildRisk :one
SELECT EXISTS (
    SELECT 1 FROM alerts WHERE child_id = $1 AND risk_score_id = $2
)
`

type ExistsAlertForChildRiskParams struct {
	ChildID     pgtype.UUID
	RiskScoreID *int64
}

// Dedup guard: has this child already been alerted for this risk score?
func (q *Queries) ExistsAlertForChildRisk(ctx context.Context, arg ExistsAlertForChildRiskParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsAlertForChildRisk, arg.ChildID, arg.RiskScoreID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAlert = `-- name: InsertAlert :one

INSERT INTO alerts (
    risk_score_id, child_id, guardian_id, area_id, vaccine_code,
    lang, channel, status, message_hash, message_id, dispatched_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertAlertParams struct {
	RiskScoreID  *int64
	ChildID      pgtype.UUID
	GuardianID   pgtype.UUID
	AreaID       string
	VaccineCode  string
	Lang         string
	Channel      string
	Status       string
	MessageHash  []byte
	MessageID    *string
	DispatchedAt pgtype.Timestamptz
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAlert,
		arg.RiskScoreID,
		arg.ChildID,
		arg.GuardianID,
		arg.AreaID,
		arg.VaccineCode,
		arg.Lang,
		arg.Channel,
		arg.Status,
		arg.MessageHash,
		arg.MessageID,
		arg.DispatchedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
