// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: areas.sql

package db

import (
	"context"
)

const listAreas = `-- name: ListAreas :many
SELECT
    id,
    name,
    level,
    ST_X(centroid)::float8 AS longitude,
    ST_Y(centroid)::float8 AS latitude
FROM areas
ORDER BY name
`

type ListAreasRow struct {
	ID        string
	Name      string
	Level     string
	Longitude float64
	Latitude  float64
}

func (q *Queries) ListAreas(ctx context.Context) ([]ListAreasRow, error) {
	rows, err := q.db.Query(ctx, listAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAreasRow
	for rows.Next() {
		var i ListAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArea = `-- name: UpsertArea :exec

INSERT INTO areas (id, name, level, centroid)
VALUES (
    $1, $2, $3,
    ST_SetSRID(ST_MakePoint($4::float8, $5::float8), 4326)
)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    level = excluded.level,
    centroid = excluded.centroid
`

type UpsertAreaParams struct {
	ID        string
	Name      string
	Level     string
	Longitude float64
	Latitude  float64
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) UpsertArea(ctx context.Context, arg UpsertAreaParams) error {
	_, err := q.db.Exec(ctx, upsertArea,
		arg.ID,
		arg.Name,
		arg.Level,
		arg.Longitude,
		arg.Latitude,
	)
	return err
}
