// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: briefings.sql

package db

import (
	"context"
)

const countBriefingsByStatus = `-- name: CountBriefingsByStatus :many
SELECT status, count(*) AS n FROM briefings GROUP BY status ORDER BY status
`

type CountBriefingsByStatusRow struct {
	Status string
	N      int64
}

func (q *Queries) CountBriefingsByStatus(ctx context.Context) ([]CountBriefingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countBriefingsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBriefingsByStatusRow
	for rows.Next() {
		var i CountBriefingsByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBriefingForKey = `-- name: GetBriefingForKey :one

SELECT id, area_id, lang, facts_hash, facts_json, generator, model,
       prompt_version, body, grounded, grounding_notes, status, created_at
FROM briefings
WHERE area_id = $1 AND lang = $2 AND facts_hash = $3
  AND generator = $4 AND model = $5 AND prompt_version = $6
`

type GetBriefingForKeyParams struct {
	AreaID        string
	Lang          string
	FactsHash     []byte
	Generator     string
	Model         string
	PromptVersion string
}

// SPDX-License-Identifier: Apache-2.0
// County risk briefings. Every row here is derived from aggregate facts only
// (see migration 0011): no query in this file reads a person's row, and none
// may be added that does.
// Cache lookup. A row for this exact key means the facts have not changed
// since that briefing was written, so nothing needs regenerating.
func (q *Queries) GetBriefingForKey(ctx context.Context, arg GetBriefingForKeyParams) (Briefing, error) {
	row := q.db.QueryRow(ctx, getBriefingForKey,
		arg.AreaID,
		arg.Lang,
		arg.FactsHash,
		arg.Generator,
		arg.Model,
		arg.PromptVersion,
	)
	var i Briefing
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Lang,
		&i.FactsHash,
		&i.FactsJson,
		&i.Generator,
		&i.Model,
		&i.PromptVersion,
		&i.Body,
		&i.Grounded,
		&i.GroundingNotes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const latestBriefing = `-- name: LatestBriefing :one
SELECT id, area_id, lang, facts_hash, facts_json, generator, model,
       prompt_version, body, grounded, grounding_notes, status, created_at
FROM briefings
WHERE area_id = $1 AND lang = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LatestBriefingParams struct {
	AreaID string
	Lang   string
}

// What the public API serves: the newest briefing for one county and language.
func (q *Queries) LatestBriefing(ctx context.Context, arg LatestBriefingParams) (Briefing, error) {
	row := q.db.QueryRow(ctx, latestBriefing, arg.AreaID, arg.Lang)
	var i Briefing
	err := row.Scan(
		&i.ID,
		&i.AreaID,
		&i.Lang,
		&i.FactsHash,
		&i.FactsJson,
		&i.Generator,
		&i.Model,
		&i.PromptVersion,
		&i.Body,
		&i.Grounded,
		&i.GroundingNotes,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBriefingAreas = `-- name: ListBriefingAreas :many
SELECT DISTINCT b.area_id, a.name AS area_name
FROM briefings b
JOIN areas a ON a.id = b.area_id
WHERE b.lang = $1
ORDER BY a.name
`

type ListBriefingAreasRow struct {
	AreaID   string
	AreaName string
}

// Counties that have at least one briefing in this language, for the API to
// tell a caller what it can ask for instead of guessing.
func (q *Queries) ListBriefingAreas(ctx context.Context, lang string) ([]ListBriefingAreasRow, error) {
	rows, err := q.db.Query(ctx, listBriefingAreas, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBriefingAreasRow
	for rows.Next() {
		var i ListBriefingAreasRow
		if err := rows.Scan(&i.AreaID, &i.AreaName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBriefing = `-- name: UpsertBriefing :one
INSERT INTO briefings (
    area_id, lang, facts_hash, facts_json, generator, model, prompt_version,
    body, grounded, grounding_notes, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (area_id, lang, facts_hash, generator, model, prompt_version)
DO UPDATE SET
    facts_json = excluded.facts_json,
    body = excluded.body,
    grounded = excluded.grounded,
    grounding_notes = excluded.grounding_notes,
    status = excluded.status,
    created_at = now()
RETURNING id
`

type UpsertBriefingParams struct {
	AreaID         string
	Lang           string
	FactsHash      []byte
	FactsJson      []byte
	Generator      string
	Model          string
	PromptVersion  string
	Body           string
	Grounded       bool
	GroundingNotes []byte
	Status         string
}

// Re-running a generation for the same facts replaces the row rather than
// accumulating duplicates: an 'unavailable' attempt becomes 'served' when the
// generator comes back, and the served text is always the latest truth.
func (q *Queries) UpsertBriefing(ctx context.Context, arg UpsertBriefingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBriefing,
		arg.AreaID,
		arg.Lang,
		arg.FactsHash,
		arg.FactsJson,
		arg.Generator,
		arg.Model,
		arg.PromptVersion,
		arg.Body,
		arg.Grounded,
		arg.GroundingNotes,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
