// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: climate.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countObservations = `-- name: CountObservations :one
SELECT count(*) FROM climate_observations
`

func (q *Queries) CountObservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countObservations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const latestObservationWindow = `-- name: LatestObservationWindow :many
SELECT co.id, co.area_id, co.forecast_date, co.issued_at, co.precipitation_sum_mm, co.temp_max_c, co.temp_min_c, co.humidity_max_pct, co.source, co.ingested_at
FROM climate_observations co
WHERE co.area_id = $1
  AND co.issued_at = (
      SELECT max(inner_co.issued_at)
      FROM climate_observations inner_co
      WHERE inner_co.area_id = $1
  )
ORDER BY co.forecast_date
`

// The most recently issued forecast batch for one area, in day order.
func (q *Queries) LatestObservationWindow(ctx context.Context, areaID string) ([]ClimateObservation, error) {
	rows, err := q.db.Query(ctx, latestObservationWindow, areaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimateObservation
	for rows.Next() {
		var i ClimateObservation
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.ForecastDate,
			&i.IssuedAt,
			&i.PrecipitationSumMm,
			&i.TempMaxC,
			&i.TempMinC,
			&i.HumidityMaxPct,
			&i.Source,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClimateObservation = `-- name: UpsertClimateObservation :exec

INSERT INTO climate_observations (
    area_id, forecast_date, issued_at,
    precipitation_sum_mm, temp_max_c, temp_min_c, humidity_max_pct, source
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (area_id, forecast_date, issued_at) DO UPDATE SET
    precipitation_sum_mm = excluded.precipitation_sum_mm,
    temp_max_c = excluded.temp_max_c,
    temp_min_c = excluded.temp_min_c,
    humidity_max_pct = excluded.humidity_max_pct,
    source = excluded.source,
    ingested_at = now()
`

type UpsertClimateObservationParams struct {
	AreaID             string
	ForecastDate       pgtype.Date
	IssuedAt           pgtype.Timestamptz
	PrecipitationSumMm float64
	TempMaxC           float64
	TempMinC           float64
	HumidityMaxPct     *float64
	Source             string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) UpsertClimateObservation(ctx context.Context, arg UpsertClimateObservationParams) error {
	_, err := q.db.Exec(ctx, upsertClimateObservation,
		arg.AreaID,
		arg.ForecastDate,
		arg.IssuedAt,
		arg.PrecipitationSumMm,
		arg.TempMaxC,
		arg.TempMinC,
		arg.HumidityMaxPct,
		arg.Source,
	)
	return err
}
