// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const destroyChildKey = `-- name: DestroyChildKey :execrows
DELETE FROM sealed.child_keys WHERE child_id = $1
`

func (q *Queries) DestroyChildKey(ctx context.Context, childID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, destroyChildKey, childID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChildKey = `-- name: GetChildKey :one
SELECT hmac_key FROM sealed.child_keys WHERE child_id = $1
`

func (q *Queries) GetChildKey(ctx context.Context, childID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getChildKey, childID)
	var hmac_key []byte
	err := row.Scan(&hmac_key)
	return hmac_key, err
}

const getDailyRoot = `-- name: GetDailyRoot :one
SELECT leaf_day, root, leaf_count, computed_at FROM daily_roots WHERE leaf_day = $1
`

func (q *Queries) GetDailyRoot(ctx context.Context, leafDay pgtype.Date) (DailyRoot, error) {
	row := q.db.QueryRow(ctx, getDailyRoot, leafDay)
	var i DailyRoot
	err := row.Scan(
		&i.LeafDay,
		&i.Root,
		&i.LeafCount,
		&i.ComputedAt,
	)
	return i, err
}

const getLeaf = `-- name: GetLeaf :one
SELECT event_id, child_id, leaf_day, leaf_hash, created_at FROM event_leaves WHERE event_id = $1
`

func (q *Queries) GetLeaf(ctx context.Context, eventID pgtype.UUID) (EventLeafe, error) {
	row := q.db.QueryRow(ctx, getLeaf, eventID)
	var i EventLeafe
	err := row.Scan(
		&i.EventID,
		&i.ChildID,
		&i.LeafDay,
		&i.LeafHash,
		&i.CreatedAt,
	)
	return i, err
}

const insertAnchor = `-- name: InsertAnchor :exec
INSERT INTO anchors (leaf_day, anchor_type, reference)
VALUES ($1, $2, $3)
`

type InsertAnchorParams struct {
	LeafDay    pgtype.Date
	AnchorType string
	Reference  *string
}

func (q *Queries) InsertAnchor(ctx context.Context, arg InsertAnchorParams) error {
	_, err := q.db.Exec(ctx, insertAnchor, arg.LeafDay, arg.AnchorType, arg.Reference)
	return err
}

const insertChildKey = `-- name: InsertChildKey :exec

INSERT INTO sealed.child_keys (child_id, hmac_key)
VALUES ($1, $2)
ON CONFLICT (child_id) DO NOTHING
`

type InsertChildKeyParams struct {
	ChildID pgtype.UUID
	HmacKey []byte
}

// SPDX-License-Identifier: Apache-2.0
// The ONLY file allowed to reference the sealed schema (per-child HMAC keys).
// scripts/contract-checks.sh enforces this.
func (q *Queries) InsertChildKey(ctx context.Context, arg InsertChildKeyParams) error {
	_, err := q.db.Exec(ctx, insertChildKey, arg.ChildID, arg.HmacKey)
	return err
}

const insertLeaf = `-- name: InsertLeaf :exec
INSERT INTO event_leaves (event_id, child_id, leaf_day, leaf_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (event_id) DO NOTHING
`

type InsertLeafParams struct {
	EventID  pgtype.UUID
	ChildID  pgtype.UUID
	LeafDay  pgtype.Date
	LeafHash []byte
}

func (q *Queries) InsertLeaf(ctx context.Context, arg InsertLeafParams) error {
	_, err := q.db.Exec(ctx, insertLeaf,
		arg.EventID,
		arg.ChildID,
		arg.LeafDay,
		arg.LeafHash,
	)
	return err
}

const leavesForDay = `-- name: LeavesForDay :many
SELECT event_id, leaf_hash
FROM event_leaves
WHERE leaf_day = $1
ORDER BY event_id
`

type LeavesForDayRow struct {
	EventID  pgtype.UUID
	LeafHash []byte
}

func (q *Queries) LeavesForDay(ctx context.Context, leafDay pgtype.Date) ([]LeavesForDayRow, error) {
	rows, err := q.db.Query(ctx, leavesForDay, leafDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeavesForDayRow
	for rows.Next() {
		var i LeavesForDayRow
		if err := rows.Scan(&i.EventID, &i.LeafHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnchorsForDay = `-- name: ListAnchorsForDay :many
SELECT id, leaf_day, anchor_type, reference, anchored_at FROM anchors WHERE leaf_day = $1 ORDER BY anchored_at, id
`

func (q *Queries) ListAnchorsForDay(ctx context.Context, leafDay pgtype.Date) ([]Anchor, error) {
	rows, err := q.db.Query(ctx, listAnchorsForDay, leafDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anchor
	for rows.Next() {
		var i Anchor
		if err := rows.Scan(
			&i.ID,
			&i.LeafDay,
			&i.AnchorType,
			&i.Reference,
			&i.AnchoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsWithoutLeaves = `-- name: ListEventsWithoutLeaves :many
SELECT ie.id, ie.child_id, ie.vaccine_code, ie.administered_at, ie.recorded_at
FROM immunization_events ie
LEFT JOIN event_leaves el ON el.event_id = ie.id
WHERE el.event_id IS NULL
ORDER BY ie.recorded_at, ie.id
`

type ListEventsWithoutLeavesRow struct {
	ID             pgtype.UUID
	ChildID        pgtype.UUID
	VaccineCode    string
	AdministeredAt pgtype.Timestamptz
	RecordedAt     pgtype.Timestamptz
}

// Immunization events the ledger has not yet committed to a Merkle leaf.
func (q *Queries) ListEventsWithoutLeaves(ctx context.Context) ([]ListEventsWithoutLeavesRow, error) {
	rows, err := q.db.Query(ctx, listEventsWithoutLeaves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsWithoutLeavesRow
	for rows.Next() {
		var i ListEventsWithoutLeavesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.VaccineCode,
			&i.AdministeredAt,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeafDays = `-- name: ListLeafDays :many
SELECT DISTINCT leaf_day FROM event_leaves ORDER BY leaf_day
`

func (q *Queries) ListLeafDays(ctx context.Context) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listLeafDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var leaf_day pgtype.Date
		if err := rows.Scan(&leaf_day); err != nil {
			return nil, err
		}
		items = append(items, leaf_day)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scrubChildFromLeaves = `-- name: ScrubChildFromLeaves :execrows
UPDATE event_leaves SET child_id = NULL WHERE child_id = $1
`

// Erasure: sever child->leaf linkage; the anonymous hash stays so daily
// roots remain structurally verifiable.
func (q *Queries) ScrubChildFromLeaves(ctx context.Context, childID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, scrubChildFromLeaves, childID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDailyRoot = `-- name: UpsertDailyRoot :exec
INSERT INTO daily_roots (leaf_day, root, leaf_count)
VALUES ($1, $2, $3)
ON CONFLICT (leaf_day) DO UPDATE SET
    root = excluded.root,
    leaf_count = excluded.leaf_count,
    computed_at = now()
`

type UpsertDailyRootParams struct {
	LeafDay   pgtype.Date
	Root      []byte
	LeafCount int32
}

func (q *Queries) UpsertDailyRoot(ctx context.Context, arg UpsertDailyRootParams) error {
	_, err := q.db.Exec(ctx, upsertDailyRoot, arg.LeafDay, arg.Root, arg.LeafCount)
	return err
}
