// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID           pgtype.UUID
	RiskScoreID  *int64
	ChildID      pgtype.UUID
	GuardianID   pgtype.UUID
	AreaID       string
	VaccineCode  string
	Lang         string
	Channel      string
	Status       string
	MessageHash  []byte
	MessageID    *string
	CreatedAt    pgtype.Timestamptz
	DispatchedAt pgtype.Timestamptz
}

type Anchor struct {
	ID         int64
	LeafDay    pgtype.Date
	AnchorType string
	Reference  *string
	AnchoredAt pgtype.Timestamptz
}

type Area struct {
	ID       string
	Name     string
	Level    string
	Centroid interface{}
}

type Child struct {
	ID          pgtype.UUID
	GuardianID  pgtype.UUID
	AreaID      string
	NameEnc     []byte
	DateOfBirth pgtype.Date
	CreatedAt   pgtype.Timestamptz
}

type ClimateObservation struct {
	ID                 int64
	AreaID             string
	ForecastDate       pgtype.Date
	IssuedAt           pgtype.Timestamptz
	PrecipitationSumMm float64
	TempMaxC           float64
	TempMinC           float64
	HumidityMaxPct     *float64
	Source             string
	IngestedAt         pgtype.Timestamptz
}

type ConsentLog struct {
	ID         int64
	GuardianID pgtype.UUID
	Action     string
	Channel    string
	OccurredAt pgtype.Timestamptz
}

type DailyRoot struct {
	LeafDay    pgtype.Date
	Root       []byte
	LeafCount  int32
	ComputedAt pgtype.Timestamptz
}

type EventLeafe struct {
	EventID   pgtype.UUID
	ChildID   pgtype.UUID
	LeafDay   pgtype.Date
	LeafHash  []byte
	CreatedAt pgtype.Timestamptz
}

type Guardian struct {
	ID            pgtype.UUID
	NameEnc       []byte
	PhoneEnc      []byte
	NationalIDEnc []byte
	Lang          string
	CreatedAt     pgtype.Timestamptz
}

type ImmunizationEvent struct {
	ID             pgtype.UUID
	ChildID        pgtype.UUID
	VaccineCode    string
	AdministeredAt pgtype.Timestamptz
	Facility       *string
	RecordedAt     pgtype.Timestamptz
}

type RiskScore struct {
	ID               int64
	AreaID           string
	Disease          string
	Level            string
	Driver           string
	DriverValue      float64
	ForecastDate     pgtype.Date
	WindowDays       int32
	Predictor        string
	PredictorVersion string
	ScoredAt         pgtype.Timestamptz
	Exceedance       *float64
	Explanation      *string
}

type SealedChildKey struct {
	ChildID   pgtype.UUID
	HmacKey   []byte
	CreatedAt pgtype.Timestamptz
}

type VaccineSchedule struct {
	Code             string
	Name             string
	DueAgeDays       int32
	OverdueGraceDays int32
}
