// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChildrenByArea = `-- name: CountChildrenByArea :many

SELECT area_id, count(*) AS n FROM children GROUP BY area_id ORDER BY area_id
`

type CountChildrenByAreaRow struct {
	AreaID string
	N      int64
}

// SPDX-License-Identifier: Apache-2.0
// Aggregate queries feeding the public tier. Everything returns counts by
// county — never rows about individual people. k-anonymity suppression is
// applied in internal/publicapi before any of these numbers leave the
// process.
func (q *Queries) CountChildrenByArea(ctx context.Context) ([]CountChildrenByAreaRow, error) {
	rows, err := q.db.Query(ctx, countChildrenByArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChildrenByAreaRow
	for rows.Next() {
		var i CountChildrenByAreaRow
		if err := rows.Scan(&i.AreaID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDispatchedAlertsByArea = `-- name: CountDispatchedAlertsByArea :many
SELECT area_id, count(*) AS n
FROM alerts
WHERE status IN ('would_send', 'sent')
GROUP BY area_id
ORDER BY area_id
`

type CountDispatchedAlertsByAreaRow struct {
	AreaID string
	N      int64
}

func (q *Queries) CountDispatchedAlertsByArea(ctx context.Context) ([]CountDispatchedAlertsByAreaRow, error) {
	rows, err := q.db.Query(ctx, countDispatchedAlertsByArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDispatchedAlertsByAreaRow
	for rows.Next() {
		var i CountDispatchedAlertsByAreaRow
		if err := rows.Scan(&i.AreaID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenForDueComputation = `-- name: ListChildrenForDueComputation :many
SELECT c.id, c.area_id, c.date_of_birth FROM children c ORDER BY c.id
`

type ListChildrenForDueComputationRow struct {
	ID          pgtype.UUID
	AreaID      string
	DateOfBirth pgtype.Date
}

// Feeds the KEPI due/overdue computation (pure Go, internal/registry). Only
// opaque ids, area and DOB — no encrypted columns are read here.
func (q *Queries) ListChildrenForDueComputation(ctx context.Context) ([]ListChildrenForDueComputationRow, error) {
	rows, err := q.db.Query(ctx, listChildrenForDueComputation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenForDueComputationRow
	for rows.Next() {
		var i ListChildrenForDueComputationRow
		if err := rows.Scan(&i.ID, &i.AreaID, &i.DateOfBirth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
