// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChildrenByArea = `-- name: CountChildrenByArea :many

SELECT area_id, count(*) AS n FROM children GROUP BY area_id ORDER BY area_id
`

type CountChildrenByAreaRow struct {
	AreaID string
	N      int64
}

// SPDX-License-Identifier: Apache-2.0
// Aggregate queries feeding the public tier. Everything returns counts by
// county — never rows about individual people. k-anonymity suppression is
// applied in internal/publicapi before any of these numbers leave the
// process.
func (q *Queries) CountChildrenByArea(ctx context.Context) ([]CountChildrenByAreaRow, error) {
	rows, err := q.db.Query(ctx, countChildrenByArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChildrenByAreaRow
	for rows.Next() {
		var i CountChildrenByAreaRow
		if err := rows.Scan(&i.AreaID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDispatchedAlertsByArea = `-- name: CountDispatchedAlertsByArea :many
SELECT area_id, count(*) AS n
FROM alerts
WHERE status IN ('would_send', 'sent')
GROUP BY area_id
ORDER BY area_id
`

type CountDispatchedAlertsByAreaRow struct {
	AreaID string
	N      int64
}

func (q *Queries) CountDispatchedAlertsByArea(ctx context.Context) ([]CountDispatchedAlertsByAreaRow, error) {
	rows, err := q.db.Query(ctx, countDispatchedAlertsByArea)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDispatchedAlertsByAreaRow
	for rows.Next() {
		var i CountDispatchedAlertsByAreaRow
		if err := rows.Scan(&i.AreaID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRiskScores = `-- name: CountRiskScores :one
SELECT count(*) FROM risk_scores
`

func (q *Queries) CountRiskScores(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRiskScores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const latestObservationIssuedAt = `-- name: LatestObservationIssuedAt :one
SELECT max(issued_at)::timestamptz FROM climate_observations
`

func (q *Queries) LatestObservationIssuedAt(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestObservationIssuedAt)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const latestSeriesForAllAreas = `-- name: LatestSeriesForAllAreas :many
SELECT co.area_id, a.name AS area_name, co.forecast_date, co.issued_at,
       co.precipitation_sum_mm, co.temp_max_c, co.temp_min_c, co.source
FROM climate_observations co
JOIN areas a ON a.id = co.area_id
WHERE co.issued_at = (
    SELECT max(inner_co.issued_at)
    FROM climate_observations inner_co
    WHERE inner_co.area_id = co.area_id
)
ORDER BY a.name, co.forecast_date
`

type LatestSeriesForAllAreasRow struct {
	AreaID             string
	AreaName           string
	ForecastDate       pgtype.Date
	IssuedAt           pgtype.Timestamptz
	PrecipitationSumMm float64
	TempMaxC           float64
	TempMinC           float64
	Source             string
}

// The most recent forecast window per area, for the climate view. Weather
// only: no person appears in this result.
func (q *Queries) LatestSeriesForAllAreas(ctx context.Context) ([]LatestSeriesForAllAreasRow, error) {
	rows, err := q.db.Query(ctx, latestSeriesForAllAreas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestSeriesForAllAreasRow
	for rows.Next() {
		var i LatestSeriesForAllAreasRow
		if err := rows.Scan(
			&i.AreaID,
			&i.AreaName,
			&i.ForecastDate,
			&i.IssuedAt,
			&i.PrecipitationSumMm,
			&i.TempMaxC,
			&i.TempMinC,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerRootSummary = `-- name: LedgerRootSummary :many
SELECT dr.leaf_day, dr.root, dr.leaf_count, dr.computed_at,
       COALESCE(an.anchor_type, '')::text AS anchor_type,
       an.anchored_at,
       an.reference AS anchor_reference,
       an.chain_id, an.chain_label, an.contract_address, an.tx_hash,
       an.block_number, an.readback_root, an.verified_at
FROM daily_roots dr
LEFT JOIN LATERAL (
    SELECT a.anchor_type, a.anchored_at, a.reference, a.chain_id, a.chain_label,
           a.contract_address, a.tx_hash, a.block_number, a.readback_root, a.verified_at
    FROM anchors a
    WHERE a.leaf_day = dr.leaf_day
    ORDER BY a.anchored_at DESC, a.id DESC
    LIMIT 1
) an ON true
ORDER BY dr.leaf_day DESC
`

type LedgerRootSummaryRow struct {
	LeafDay         pgtype.Date
	Root            []byte
	LeafCount       int32
	ComputedAt      pgtype.Timestamptz
	AnchorType      string
	AnchoredAt      pgtype.Timestamptz
	AnchorReference *string
	ChainID         *int64
	ChainLabel      *string
	ContractAddress *string
	TxHash          *string
	BlockNumber     *int64
	ReadbackRoot    []byte
	VerifiedAt      pgtype.Timestamptz
}

// Daily Merkle roots and their anchors. A root is a commitment over a whole
// day; no individual leaf is selected here and none may ever be published.
// Only the NEWEST anchor per day is returned: the number of anchor versions
// a day accumulated would track how many late immunizations were recorded,
// which is a people-derived count.
func (q *Queries) LedgerRootSummary(ctx context.Context) ([]LedgerRootSummaryRow, error) {
	rows, err := q.db.Query(ctx, ledgerRootSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerRootSummaryRow
	for rows.Next() {
		var i LedgerRootSummaryRow
		if err := rows.Scan(
			&i.LeafDay,
			&i.Root,
			&i.LeafCount,
			&i.ComputedAt,
			&i.AnchorType,
			&i.AnchoredAt,
			&i.AnchorReference,
			&i.ChainID,
			&i.ChainLabel,
			&i.ContractAddress,
			&i.TxHash,
			&i.BlockNumber,
			&i.ReadbackRoot,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenForDueComputation = `-- name: ListChildrenForDueComputation :many
SELECT c.id, c.area_id, c.date_of_birth FROM children c ORDER BY c.id
`

type ListChildrenForDueComputationRow struct {
	ID          pgtype.UUID
	AreaID      string
	DateOfBirth pgtype.Date
}

// Feeds the KEPI due/overdue computation (pure Go, internal/registry). Only
// opaque ids, area and DOB — no encrypted columns are read here.
func (q *Queries) ListChildrenForDueComputation(ctx context.Context) ([]ListChildrenForDueComputationRow, error) {
	rows, err := q.db.Query(ctx, listChildrenForDueComputation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenForDueComputationRow
	for rows.Next() {
		var i ListChildrenForDueComputationRow
		if err := rows.Scan(&i.ID, &i.AreaID, &i.DateOfBirth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
