// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendConsent = `-- name: AppendConsent :exec
INSERT INTO consent_log (guardian_id, action, channel)
VALUES ($1, $2, $3)
`

type AppendConsentParams struct {
	GuardianID pgtype.UUID
	Action     string
	Channel    string
}

func (q *Queries) AppendConsent(ctx context.Context, arg AppendConsentParams) error {
	_, err := q.db.Exec(ctx, appendConsent, arg.GuardianID, arg.Action, arg.Channel)
	return err
}

const createChild = `-- name: CreateChild :one
INSERT INTO children (guardian_id, area_id, name_enc, date_of_birth)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateChildParams struct {
	GuardianID  pgtype.UUID
	AreaID      string
	NameEnc     []byte
	DateOfBirth pgtype.Date
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createChild,
		arg.GuardianID,
		arg.AreaID,
		arg.NameEnc,
		arg.DateOfBirth,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createGuardian = `-- name: CreateGuardian :one

INSERT INTO guardians (name_enc, phone_enc, national_id_enc, lang)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateGuardianParams struct {
	NameEnc       []byte
	PhoneEnc      []byte
	NationalIDEnc []byte
	Lang          string
}

// SPDX-License-Identifier: Apache-2.0
// immunization_events is append-only: INSERT and SELECT only in this file,
// with one exception — EraseChildEvents, the guarded erasure path used by
// ForgetChild. It only works inside a transaction that has set
// climateshield.allow_erasure = 'on' (see the trigger in migration 0005);
// otherwise the trigger raises. UPDATE is never allowed for any caller.
func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGuardian,
		arg.NameEnc,
		arg.PhoneEnc,
		arg.NationalIDEnc,
		arg.Lang,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteChild = `-- name: DeleteChild :exec
DELETE FROM children WHERE id = $1
`

func (q *Queries) DeleteChild(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChild, id)
	return err
}

const eraseChildEvents = `-- name: EraseChildEvents :execrows
DELETE FROM immunization_events WHERE child_id = $1
`

func (q *Queries) EraseChildEvents(ctx context.Context, childID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, eraseChildEvents, childID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChild = `-- name: GetChild :one
SELECT id, guardian_id, area_id, name_enc, date_of_birth, created_at FROM children WHERE id = $1
`

func (q *Queries) GetChild(ctx context.Context, id pgtype.UUID) (Child, error) {
	row := q.db.QueryRow(ctx, getChild, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.GuardianID,
		&i.AreaID,
		&i.NameEnc,
		&i.DateOfBirth,
		&i.CreatedAt,
	)
	return i, err
}

const getGuardian = `-- name: GetGuardian :one
SELECT id, name_enc, phone_enc, national_id_enc, lang, created_at FROM guardians WHERE id = $1
`

func (q *Queries) GetGuardian(ctx context.Context, id pgtype.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardian, id)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.NameEnc,
		&i.PhoneEnc,
		&i.NationalIDEnc,
		&i.Lang,
		&i.CreatedAt,
	)
	return i, err
}

const getImmunizationEvent = `-- name: GetImmunizationEvent :one
SELECT id, child_id, vaccine_code, administered_at, facility, recorded_at FROM immunization_events WHERE id = $1
`

func (q *Queries) GetImmunizationEvent(ctx context.Context, id pgtype.UUID) (ImmunizationEvent, error) {
	row := q.db.QueryRow(ctx, getImmunizationEvent, id)
	var i ImmunizationEvent
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.VaccineCode,
		&i.AdministeredAt,
		&i.Facility,
		&i.RecordedAt,
	)
	return i, err
}

const insertImmunizationEvent = `-- name: InsertImmunizationEvent :one
INSERT INTO immunization_events (child_id, vaccine_code, administered_at, facility)
VALUES ($1, $2, $3, $4)
RETURNING id, recorded_at
`

type InsertImmunizationEventParams struct {
	ChildID        pgtype.UUID
	VaccineCode    string
	AdministeredAt pgtype.Timestamptz
	Facility       *string
}

type InsertImmunizationEventRow struct {
	ID         pgtype.UUID
	RecordedAt pgtype.Timestamptz
}

func (q *Queries) InsertImmunizationEvent(ctx context.Context, arg InsertImmunizationEventParams) (InsertImmunizationEventRow, error) {
	row := q.db.QueryRow(ctx, insertImmunizationEvent,
		arg.ChildID,
		arg.VaccineCode,
		arg.AdministeredAt,
		arg.Facility,
	)
	var i InsertImmunizationEventRow
	err := row.Scan(&i.ID, &i.RecordedAt)
	return i, err
}

const latestConsent = `-- name: LatestConsent :one
SELECT action
FROM consent_log
WHERE guardian_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestConsent(ctx context.Context, guardianID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, latestConsent, guardianID)
	var action string
	err := row.Scan(&action)
	return action, err
}

const listChildren = `-- name: ListChildren :many
SELECT id, guardian_id, area_id, name_enc, date_of_birth, created_at FROM children ORDER BY created_at, id
`

func (q *Queries) ListChildren(ctx context.Context) ([]Child, error) {
	rows, err := q.db.Query(ctx, listChildren)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Child
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.GuardianID,
			&i.AreaID,
			&i.NameEnc,
			&i.DateOfBirth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForChild = `-- name: ListEventsForChild :many
SELECT id, child_id, vaccine_code, administered_at, facility, recorded_at FROM immunization_events WHERE child_id = $1 ORDER BY administered_at, id
`

func (q *Queries) ListEventsForChild(ctx context.Context, childID pgtype.UUID) ([]ImmunizationEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImmunizationEvent
	for rows.Next() {
		var i ImmunizationEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.VaccineCode,
			&i.AdministeredAt,
			&i.Facility,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImmunizationPairs = `-- name: ListImmunizationPairs :many
SELECT child_id, vaccine_code FROM immunization_events
`

type ListImmunizationPairsRow struct {
	ChildID     pgtype.UUID
	VaccineCode string
}

func (q *Queries) ListImmunizationPairs(ctx context.Context) ([]ListImmunizationPairsRow, error) {
	rows, err := q.db.Query(ctx, listImmunizationPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImmunizationPairsRow
	for rows.Next() {
		var i ListImmunizationPairsRow
		if err := rows.Scan(&i.ChildID, &i.VaccineCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaccineSchedule = `-- name: ListVaccineSchedule :many
SELECT code, name, due_age_days, overdue_grace_days FROM vaccine_schedule ORDER BY due_age_days, code
`

func (q *Queries) ListVaccineSchedule(ctx context.Context) ([]VaccineSchedule, error) {
	rows, err := q.db.Query(ctx, listVaccineSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VaccineSchedule
	for rows.Next() {
		var i VaccineSchedule
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.DueAgeDays,
			&i.OverdueGraceDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
