// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: risk.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentRisk = `-- name: CurrentRisk :many
SELECT DISTINCT ON (rs.area_id, rs.disease)
    rs.id, rs.area_id, rs.disease, rs.level, rs.driver, rs.driver_value,
    rs.forecast_date, rs.window_days, rs.predictor, rs.predictor_version,
    rs.exceedance, rs.explanation, rs.scored_at,
    a.name AS area_name,
    ST_X(a.centroid)::float8 AS longitude,
    ST_Y(a.centroid)::float8 AS latitude
FROM risk_scores rs
JOIN areas a ON a.id = rs.area_id
ORDER BY rs.area_id, rs.disease, rs.forecast_date DESC, rs.scored_at DESC
`

type CurrentRiskRow struct {
	ID               int64
	AreaID           string
	Disease          string
	Level            string
	Driver           string
	DriverValue      float64
	ForecastDate     pgtype.Date
	WindowDays       int32
	Predictor        string
	PredictorVersion string
	Exceedance       *float64
	Explanation      *string
	ScoredAt         pgtype.Timestamptz
	AreaName         string
	Longitude        float64
	Latitude         float64
}

// Latest score per area x disease, joined with the county centroid for maps.
func (q *Queries) CurrentRisk(ctx context.Context) ([]CurrentRiskRow, error) {
	rows, err := q.db.Query(ctx, currentRisk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentRiskRow
	for rows.Next() {
		var i CurrentRiskRow
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.Disease,
			&i.Level,
			&i.Driver,
			&i.DriverValue,
			&i.ForecastDate,
			&i.WindowDays,
			&i.Predictor,
			&i.PredictorVersion,
			&i.Exceedance,
			&i.Explanation,
			&i.ScoredAt,
			&i.AreaName,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const riskHistory = `-- name: RiskHistory :many
SELECT
    rs.id, rs.area_id, rs.disease, rs.level, rs.driver, rs.driver_value,
    rs.forecast_date, rs.window_days, rs.predictor, rs.predictor_version,
    rs.exceedance, rs.explanation, rs.scored_at,
    a.name AS area_name,
    ST_X(a.centroid)::float8 AS longitude,
    ST_Y(a.centroid)::float8 AS latitude
FROM risk_scores rs
JOIN areas a ON a.id = rs.area_id
WHERE ($1::text IS NULL OR a.name = $1)
  AND ($2::text IS NULL OR rs.disease = $2)
  AND ($3::date IS NULL OR rs.forecast_date >= $3)
  AND ($4::date IS NULL OR rs.forecast_date <= $4)
ORDER BY rs.forecast_date DESC, a.name, rs.disease
LIMIT $5
`

type RiskHistoryParams struct {
	AreaName *string
	Disease  *string
	FromDate pgtype.Date
	ToDate   pgtype.Date
	RowLimit int32
}

type RiskHistoryRow struct {
	ID               int64
	AreaID           string
	Disease          string
	Level            string
	Driver           string
	DriverValue      float64
	ForecastDate     pgtype.Date
	WindowDays       int32
	Predictor        string
	PredictorVersion string
	Exceedance       *float64
	Explanation      *string
	ScoredAt         pgtype.Timestamptz
	AreaName         string
	Longitude        float64
	Latitude         float64
}

func (q *Queries) RiskHistory(ctx context.Context, arg RiskHistoryParams) ([]RiskHistoryRow, error) {
	rows, err := q.db.Query(ctx, riskHistory,
		arg.AreaName,
		arg.Disease,
		arg.FromDate,
		arg.ToDate,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiskHistoryRow
	for rows.Next() {
		var i RiskHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.AreaID,
			&i.Disease,
			&i.Level,
			&i.Driver,
			&i.DriverValue,
			&i.ForecastDate,
			&i.WindowDays,
			&i.Predictor,
			&i.PredictorVersion,
			&i.Exceedance,
			&i.Explanation,
			&i.ScoredAt,
			&i.AreaName,
			&i.Longitude,
			&i.Latitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRiskScore = `-- name: UpsertRiskScore :one

INSERT INTO risk_scores (
    area_id, disease, level, driver, driver_value,
    forecast_date, window_days, predictor, predictor_version,
    exceedance, explanation
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (area_id, disease, forecast_date) DO UPDATE SET
    level = excluded.level,
    driver = excluded.driver,
    driver_value = excluded.driver_value,
    window_days = excluded.window_days,
    predictor = excluded.predictor,
    predictor_version = excluded.predictor_version,
    exceedance = excluded.exceedance,
    explanation = excluded.explanation,
    scored_at = now()
RETURNING id
`

type UpsertRiskScoreParams struct {
	AreaID           string
	Disease          string
	Level            string
	Driver           string
	DriverValue      float64
	ForecastDate     pgtype.Date
	WindowDays       int32
	Predictor        string
	PredictorVersion string
	Exceedance       *float64
	Explanation      *string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) UpsertRiskScore(ctx context.Context, arg UpsertRiskScoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRiskScore,
		arg.AreaID,
		arg.Disease,
		arg.Level,
		arg.Driver,
		arg.DriverValue,
		arg.ForecastDate,
		arg.WindowDays,
		arg.Predictor,
		arg.PredictorVersion,
		arg.Exceedance,
		arg.Explanation,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
