#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Brings the ClimateShield demonstration up on a fresh Debian or Ubuntu host —
# a DigitalOcean droplet, or anything else with a public IP and root.
#
# Run it ON THE HOST, as root:
#
#   git clone https://github.com/jarida-io/climateshield.git
#   cd climateshield && git checkout <ref>
#   ./scripts/deploy-droplet.sh
#
# It is idempotent: run it again after a `git pull` to update in place. It
# never overwrites an existing .env, so the secrets generated on the first run
# survive every later one.
#
# WHAT IT DEPLOYS: a demonstration carrying FICTIONAL seed data only. The demo
# population is invented and the phone numbers are a fake +2547000001xx range.
# Nothing here is fit to hold real records about real children — see "Before
# this could hold real data" in deploy/README.md.
set -euo pipefail
cd "$(dirname "$0")/.."

C="docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml"

say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# --- 1. Host packages -------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  say "Installing Docker"
  apt-get update -qq
  apt-get install -y -qq docker.io docker-compose-plugin git openssl >/dev/null
  systemctl enable --now docker
else
  say "Docker already present: $(docker --version)"
fi

# --- 2. Firewall ------------------------------------------------------------
# Only SSH and the two web ports. Postgres, the registry, the public API and
# the development chain are reachable only inside the compose network, which
# the production overlay enforces by publishing no host port for any of them.
if command -v ufw >/dev/null 2>&1; then
  say "Firewall: allowing SSH, 80 and 443 only"
  ufw --force reset >/dev/null 2>&1 || true
  ufw default deny incoming >/dev/null
  ufw default allow outgoing >/dev/null
  ufw allow OpenSSH >/dev/null
  ufw allow 80/tcp >/dev/null
  ufw allow 443/tcp >/dev/null
  ufw --force enable >/dev/null
  ufw status verbose | sed 's/^/    /'
else
  echo "    ufw not installed; skipping firewall configuration" >&2
fi

# --- 3. Secrets, generated here and never printed ---------------------------
# Note what is absent: PII_ALLOW_DEV_KEY. Without it the services refuse to
# start on the placeholder key published in .env.example, so a deployment that
# skips this step fails loudly rather than running with encryption that
# protects nothing.
if [ -f .env ]; then
  say "Keeping the existing .env (delete it yourself to rotate secrets)"
else
  say "Generating secrets on this host"
  PG_PASS="$(openssl rand -hex 24)"
  # SITE_ADDRESS: a domain gets automatic HTTPS from Caddy. A bare IP cannot be
  # issued a certificate, so an IP-only demo is served over plain HTTP on :80.
  SITE="${SITE_ADDRESS:-:80}"
  umask 077
  cat > .env <<EOF
# Generated by scripts/deploy-droplet.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# These values exist only on this host. Do not copy them anywhere.
POSTGRES_USER=climateshield
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=climateshield
DATABASE_URL=postgres://climateshield:${PG_PASS}@postgres:5432/climateshield?sslmode=disable
PII_KEY_HEX=$(openssl rand -hex 32)

CLIMATE_SOURCE=${CLIMATE_SOURCE:-fixture}
NOTIFY_CHANNEL=mock
PREDICTOR=${PREDICTOR:-rules}
LOG_LEVEL=info

# Daily Merkle roots are anchored to the development chain this stack starts.
# The overlay publishes no port for it; it is reachable only from the ledger
# and the public API. It is not a public network and holds no value.
ANCHOR_MODE=evm
ANCHOR_RPC_URL=http://anvil:8545

# The briefing generator stays deterministic: no language model, no credential.
BRIEFING_GENERATOR=mock

SITE_ADDRESS=${SITE}
EOF
  chmod 600 .env
  echo "    wrote .env (0600). The secrets were not printed."
fi

# --- 4. Build and start -----------------------------------------------------
say "Building and starting (first run compiles eight Go binaries and the dashboard)"
$C up -d --build --wait
$C ps

# --- 5. Seed the demonstration ----------------------------------------------
# Runs inside the compose network, so it reaches postgres, registry and
# publicapi by service name without reopening a single port.
say "Seeding the fictional demo population and running the pipeline"
$C --profile demo run --rm demo || echo "    demo exited non-zero; the stack is still up — check 'logs demo'"

# --- 6. Verify --------------------------------------------------------------
say "Verifying from the host"
echo "--- /health"
curl -fsS localhost/health || echo "    health check failed"
echo
echo "--- the chain anchor, re-read live from the contract"
curl -fsS "localhost/v1/ledger/anchors/verify" || echo "    verification endpoint failed"
echo
echo "--- k-anonymity: counties under ten are withheld"
curl -fsS localhost/v1/stats || echo "    stats failed"
echo

say "Confirm the database is NOT reachable from outside"
echo "    From your laptop, this must be refused:  nc -vz $(hostname -I 2>/dev/null | awk '{print $1}') 5432"

say "Done. Dashboard: http://$(hostname -I 2>/dev/null | awk '{print $1}')/"
