# SPDX-License-Identifier: Apache-2.0
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /v1/ {
        proxy_pass http://publicapi:8080;
    }
    location /health {
        proxy_pass http://publicapi:8080;
    }
    location /climateshield.v1.PublicService/ {
        proxy_pass http://publicapi:8080;
    }
    location / {
        try_files $uri /index.html;
    }
}
